### ISSUE TITLE
Suggestion - change service binary name

### ISSUE THREAD

**Issue by mavjs** [engineersmy/lookie#17]
Putting this into an issue report since we chatted about this in slack PM.

It would be good to rename the server command to `lookie/cmd/lookie-server` or `lookie/cmd/lookie`, since `lookie/cmd/server` is too generic of a name if/when beginners use `go get github.com/lookie/cmd/server` to run the service.

This isn't an issue if used inside a container, but likely most beginners will go with the above scenario, and could cause problems down the road. (Some other command could be using `server` too.)

**Comment by klrkdekira** [comment]
Updated at 9e3f6283458045aa43c8d744d44d83723ee46653.
